name: "Generate backlog"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'auto sync coffee') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3
      - name: Run bc tool
        run: ./tools/bc-linux-amd64 backlog Beanconqueror.zip | jq .available_beans > data/backlog.json
      - name: "Commit changes"
        run: |
          git config --global user.name "Marcel Blijleven"
          git config --global user.email "marcelblijleven@users.noreply.github.com"
          git commit -am "coffee: generate backlog" || echo "No changes detected^"
          git push
